name: Deploy github pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v3
      
      - name: Install dependencies
        run: npm install -D

      - name: Build
        run: npm run build
      
      - name: Deploy
        run: npm run deploy